# Generated by Django 2.1.2 on 2018-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_category',
            field=models.CharField(choices=[('1', '鞋服配饰'), ('2', '生活用品'), ('3', '交通工具'), ('4', '图书电子')], max_length=5),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_subcategory',
            field=models.CharField(choices=[('1', '女装'), ('2', '男装'), ('3', '鞋靴'), ('4', '配饰箱包'), ('5', '美妆洗护'), ('6', '家具'), ('7', '家纺/家饰'), ('8', '百货'), ('9', '自行车'), ('10', '电动车'), ('11', '配饰/箱包'), ('12', '图书'), ('13', '文具'), ('14', '数码/电器')], max_length=6),
        ),
    ]
