# Generated by Django 2.1.2 on 2018-11-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20181117_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
